# Theme metadata
name = "Minimal"

# Is theme light or dark?
light = true

# Primary
primary = "#76518C"

# Menu
menu_primary = "#fff"
menu_text = "#126607"
menu_text_active = "#76518C"
menu_title = "#2b2b2b"

# Home sections
home_section_odd = "rgb(255, 255, 255)"
home_section_even = "rgb(247, 247, 247)"
